language: haskell

ghc:
  - "8.x"

# Only clone the most recent commit.
git:
  depth: 1

branches:
  only:
    - master

# Don't email me
notifications:
  email: false

install:
  - cabal install alex
  - export PATH=~/.cabal/bin:${PATH}

script:
  - make